- name: Check prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yml
  tags:
    - prerequisites

- name: Install/Configure Dependencies
  ansible.builtin.include_tasks:
    file: dependencies.yml
  tags:
    - dependencies

- name: Install Kuiper
  ansible.builtin.include_tasks:
    file: install_kuiper.yml
  tags:
    - install_kuiper
